import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/terms-of-service")({
  head: () => ({
    meta: [
      { title: "CuraQ | Terms of Service" },
      { name: "description", content: "Terms of Service for CuraQ." },
    ],
  }),
  component: TermsOfService,
});

function TermsOfService() {
  return (
    <div className="on-landing">
      <style>{css}</style>
      
      <header className="on-nav-wrap">
        <nav className="on-nav">
          <Link to="/" className="on-brand">
            <img src="/app/assets/logo.png" alt="" />
            <span>CuraQ</span>
          </Link>
          <div className="on-nav-cta">
            <Link to="/" className="on-btn on-btn-ghost">Back to Home</Link>
          </div>
        </nav>
      </header>

      <section className="on-hero" style={{ paddingBottom: '40px' }}>
        <div className="on-hero-inner" style={{ gridTemplateColumns: '1fr', textAlign: 'center' }}>
          <div className="on-hero-copy" style={{ margin: '0 auto' }}>
            <h1>Terms of Service</h1>
            <p className="on-lede" style={{ margin: '0 auto' }}>
              The rules and guidelines for using the CuraQ platform.
            </p>
          </div>
        </div>
      </section>

      <section className="on-section" style={{ paddingTop: '40px', maxWidth: '800px', margin: '0 auto' }}>
        <div className="policy-content">
          <p><strong>Effective Date:</strong> August 2026</p>
          
          <h3>1. Acceptance of Terms</h3>
          <p>
            By accessing or using CuraQ, you agree to be bound by these Terms of Service. If you do not agree to all of the terms and conditions, you must not use our service.
          </p>

          <h3>2. Educational Purpose & Medical Disclaimer</h3>
          <p>
            CuraQ is designed as an educational tool for university and medical students. The AI-generated flashcards, MCQs, and explanations are for <strong>study purposes only</strong>. CuraQ does not provide medical advice, diagnosis, or treatment. You must never use the information generated by this platform to make clinical decisions or treat patients. Always refer to official medical literature and consult qualified healthcare professionals.
          </p>

          <h3>3. Acceptable Use</h3>
          <p>
            You agree to use CuraQ only for lawful purposes. You are strictly prohibited from:
            <ul>
              <li>Uploading copyrighted material that you do not have the right to use or distribute.</li>
              <li>Attempting to reverse engineer, abuse, or systematically scrape our AI APIs or infrastructure.</li>
              <li>Using the platform to generate illegal, hateful, or harmful content.</li>
            </ul>
            We reserve the right to suspend or terminate accounts that violate these rules.
          </p>

          <h3>4. User Content</h3>
          <p>
            You retain full ownership of any documents you upload. By uploading content to CuraQ, you grant us a temporary license to process this data exclusively to generate your study materials. We do not claim ownership over your files or notes.
          </p>

          <h3>5. "As Is" Service</h3>
          <p>
            CuraQ is provided 100% free of charge and on an "as is" and "as available" basis. While we strive for high accuracy and uptime, we make no warranties that the service will be uninterrupted, error-free, or that the AI-generated content is entirely accurate. You use the service at your own risk.
          </p>

          <h3>6. Contact Us</h3>
          <p>
            If you have questions about these Terms, please log in to your account and open a support ticket from your dashboard.
          </p>
        </div>
      </section>

      <footer className="on-foot">
        <div className="on-foot-inner">
          <Link to="/" className="on-brand">
            <img src="/app/assets/logo.png" alt="" />
            <span>CuraQ</span>
          </Link>
          <div className="on-foot-links">
            <Link to="/terms-of-service">Terms of Service</Link>
            <Link to="/privacy-policy">Privacy Policy</Link>
            <Link to="/refund-policy">Refund Policy</Link>
            <Link to="/contact-us">Contact Us</Link>
          </div>
          <div className="on-foot-copy">© {new Date().getFullYear()} CuraQ</div>
        </div>
      </footer>
    </div>
  );
}

const css = `
.on-landing { min-height: 100vh; background: #ffffff; color: #0a3d4a; font-family: 'Figtree', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; -webkit-font-smoothing: antialiased; }
.on-landing *, .on-landing *::before, .on-landing *::after { box-sizing: border-box; }
.on-landing a { text-decoration: none; color: inherit; }
.on-landing h1, .on-landing h2, .on-landing h3, .on-landing h4 { font-family: 'Outfit', 'Figtree', sans-serif; color: #0a3d4a; margin: 0; letter-spacing: -0.02em; font-weight: 700; }
.on-landing p, .on-landing li { color: #334e59; margin: 0; }

.on-nav-wrap { position: sticky; top: 0; z-index: 50; background: rgba(255,255,255,0.92); backdrop-filter: saturate(140%) blur(8px); border-bottom: 1px solid #e4eaee; }
.on-nav { max-width: 1200px; margin: 0 auto; display: flex; align-items: center; justify-content: space-between; gap: 24px; padding: 14px 24px; }
.on-brand { display: flex; align-items: center; gap: 10px; font-family: 'Outfit', sans-serif; font-weight: 800; font-size: 19px; color: #0a3d4a; }
.on-brand img { width: 28px; height: 28px; border-radius: 6px; }
.on-nav-cta { display: flex; gap: 8px; }

.on-btn { display: inline-flex; align-items: center; justify-content: center; gap: 8px; padding: 10px 18px; border-radius: 8px; font-family: inherit; font-size: 14.5px; font-weight: 600; border: 1px solid transparent; cursor: pointer; transition: background .15s ease, color .15s ease, border-color .15s ease; white-space: nowrap; }
.on-btn-ghost { background: transparent; color: #0a3d4a; }
.on-btn-ghost:hover { background: #eef4f5; }

.on-hero { padding: 72px 24px 88px; background: linear-gradient(180deg, #ffffff 0%, #f4f6f8 100%); border-bottom: 1px solid #eef2f4; }
.on-hero-inner { max-width: 1200px; margin: 0 auto; display: grid; }
.on-hero-copy h1 { font-size: clamp(38px, 5.6vw, 62px); line-height: 1.05; margin-bottom: 20px; font-weight: 800; }
.on-lede { font-size: 17px; line-height: 1.6; color: #334e59; max-width: 560px; margin-bottom: 28px; }

.on-section { max-width: 1200px; margin: 0 auto; padding: 96px 24px; }
.policy-content h3 { font-size: 22px; margin: 32px 0 16px 0; }
.policy-content p, .policy-content li { font-size: 16px; line-height: 1.7; margin-bottom: 16px; color: #334e59; }
.policy-content ul { padding-left: 24px; margin-bottom: 16px; }

.on-foot { background: #f4f6f8; border-top: 1px solid #e4eaee; margin-top: 64px; }
.on-foot-inner { max-width: 1200px; margin: 0 auto; padding: 32px 24px; display: flex; align-items: center; justify-content: space-between; gap: 20px; }
.on-foot-links { display: flex; gap: 20px; font-size: 14px; color: #334e59; }
.on-foot-links a { text-decoration: none; color: inherit; }
.on-foot-links a:hover { color: #0e7c86; }
.on-foot-copy { font-size: 13px; color: #90a2ab; }
`;
