/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as ApiActivityRouteImport } from './routes/api/activity'
import { Route as ApiAdminRouteImport } from './routes/api/admin'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as ApiKashierRouteImport } from './routes/api/kashier'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiQbankRouteImport } from './routes/api/qbank'
import { Route as ApiSupportRouteImport } from './routes/api/support'
import { Route as ApiPublicPeerStatsThresholdRouteImport } from './routes/api/public/peer-stats-threshold'
import { Route as ApiPublicQbanksRouteImport } from './routes/api/public/qbanks'
import { Route as ApiPublicYoutubeTranscriptRouteImport } from './routes/api/public/youtube-transcript'
import { Route as ApiPublicKashierRenewRouteImport } from './routes/api/public/kashier/renew'
import { Route as ApiPublicKashierReturnRouteImport } from './routes/api/public/kashier/return'
import { Route as ApiPublicKashierWebhookRouteImport } from './routes/api/public/kashier/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivityRoute = ApiActivityRouteImport.update({
  id: '/api/activity',
  path: '/api/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKashierRoute = ApiKashierRouteImport.update({
  id: '/api/kashier',
  path: '/api/kashier',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQbankRoute = ApiQbankRouteImport.update({
  id: '/api/qbank',
  path: '/api/qbank',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupportRoute = ApiSupportRouteImport.update({
  id: '/api/support',
  path: '/api/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPeerStatsThresholdRoute =
  ApiPublicPeerStatsThresholdRouteImport.update({
    id: '/api/public/peer-stats-threshold',
    path: '/api/public/peer-stats-threshold',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicQbanksRoute = ApiPublicQbanksRouteImport.update({
  id: '/api/public/qbanks',
  path: '/api/public/qbanks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicYoutubeTranscriptRoute =
  ApiPublicYoutubeTranscriptRouteImport.update({
    id: '/api/public/youtube-transcript',
    path: '/api/public/youtube-transcript',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKashierRenewRoute = ApiPublicKashierRenewRouteImport.update({
  id: '/api/public/kashier/renew',
  path: '/api/public/kashier/renew',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKashierReturnRoute = ApiPublicKashierReturnRouteImport.update({
  id: '/api/public/kashier/return',
  path: '/api/public/kashier/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKashierWebhookRoute = ApiPublicKashierWebhookRouteImport.update({
  id: '/api/public/kashier/webhook',
  path: '/api/public/kashier/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/ai': typeof ApiAiRoute
  '/api/kashier': typeof ApiKashierRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/qbank': typeof ApiQbankRoute
  '/api/support': typeof ApiSupportRoute
  '/api/public/peer-stats-threshold': typeof ApiPublicPeerStatsThresholdRoute
  '/api/public/qbanks': typeof ApiPublicQbanksRoute
  '/api/public/youtube-transcript': typeof ApiPublicYoutubeTranscriptRoute
  '/api/public/kashier/renew': typeof ApiPublicKashierRenewRoute
  '/api/public/kashier/return': typeof ApiPublicKashierReturnRoute
  '/api/public/kashier/webhook': typeof ApiPublicKashierWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/ai': typeof ApiAiRoute
  '/api/kashier': typeof ApiKashierRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/qbank': typeof ApiQbankRoute
  '/api/support': typeof ApiSupportRoute
  '/api/public/peer-stats-threshold': typeof ApiPublicPeerStatsThresholdRoute
  '/api/public/qbanks': typeof ApiPublicQbanksRoute
  '/api/public/youtube-transcript': typeof ApiPublicYoutubeTranscriptRoute
  '/api/public/kashier/renew': typeof ApiPublicKashierRenewRoute
  '/api/public/kashier/return': typeof ApiPublicKashierReturnRoute
  '/api/public/kashier/webhook': typeof ApiPublicKashierWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/ai': typeof ApiAiRoute
  '/api/kashier': typeof ApiKashierRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/qbank': typeof ApiQbankRoute
  '/api/support': typeof ApiSupportRoute
  '/api/public/peer-stats-threshold': typeof ApiPublicPeerStatsThresholdRoute
  '/api/public/qbanks': typeof ApiPublicQbanksRoute
  '/api/public/youtube-transcript': typeof ApiPublicYoutubeTranscriptRoute
  '/api/public/kashier/renew': typeof ApiPublicKashierRenewRoute
  '/api/public/kashier/return': typeof ApiPublicKashierReturnRoute
  '/api/public/kashier/webhook': typeof ApiPublicKashierWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact-us'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-of-service'
    | '/api/activity'
    | '/api/admin'
    | '/api/ai'
    | '/api/kashier'
    | '/api/notifications'
    | '/api/qbank'
    | '/api/support'
    | '/api/public/peer-stats-threshold'
    | '/api/public/qbanks'
    | '/api/public/youtube-transcript'
    | '/api/public/kashier/renew'
    | '/api/public/kashier/return'
    | '/api/public/kashier/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact-us'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-of-service'
    | '/api/activity'
    | '/api/admin'
    | '/api/ai'
    | '/api/kashier'
    | '/api/notifications'
    | '/api/qbank'
    | '/api/support'
    | '/api/public/peer-stats-threshold'
    | '/api/public/qbanks'
    | '/api/public/youtube-transcript'
    | '/api/public/kashier/renew'
    | '/api/public/kashier/return'
    | '/api/public/kashier/webhook'
  id:
    | '__root__'
    | '/'
    | '/contact-us'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-of-service'
    | '/api/activity'
    | '/api/admin'
    | '/api/ai'
    | '/api/kashier'
    | '/api/notifications'
    | '/api/qbank'
    | '/api/support'
    | '/api/public/peer-stats-threshold'
    | '/api/public/qbanks'
    | '/api/public/youtube-transcript'
    | '/api/public/kashier/renew'
    | '/api/public/kashier/return'
    | '/api/public/kashier/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactUsRoute: typeof ContactUsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ApiActivityRoute: typeof ApiActivityRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiKashierRoute: typeof ApiKashierRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiQbankRoute: typeof ApiQbankRoute
  ApiSupportRoute: typeof ApiSupportRoute
  ApiPublicPeerStatsThresholdRoute: typeof ApiPublicPeerStatsThresholdRoute
  ApiPublicQbanksRoute: typeof ApiPublicQbanksRoute
  ApiPublicYoutubeTranscriptRoute: typeof ApiPublicYoutubeTranscriptRoute
  ApiPublicKashierRenewRoute: typeof ApiPublicKashierRenewRoute
  ApiPublicKashierReturnRoute: typeof ApiPublicKashierReturnRoute
  ApiPublicKashierWebhookRoute: typeof ApiPublicKashierWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activity': {
      id: '/api/activity'
      path: '/api/activity'
      fullPath: '/api/activity'
      preLoaderRoute: typeof ApiActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kashier': {
      id: '/api/kashier'
      path: '/api/kashier'
      fullPath: '/api/kashier'
      preLoaderRoute: typeof ApiKashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qbank': {
      id: '/api/qbank'
      path: '/api/qbank'
      fullPath: '/api/qbank'
      preLoaderRoute: typeof ApiQbankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/support': {
      id: '/api/support'
      path: '/api/support'
      fullPath: '/api/support'
      preLoaderRoute: typeof ApiSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/peer-stats-threshold': {
      id: '/api/public/peer-stats-threshold'
      path: '/api/public/peer-stats-threshold'
      fullPath: '/api/public/peer-stats-threshold'
      preLoaderRoute: typeof ApiPublicPeerStatsThresholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/qbanks': {
      id: '/api/public/qbanks'
      path: '/api/public/qbanks'
      fullPath: '/api/public/qbanks'
      preLoaderRoute: typeof ApiPublicQbanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/youtube-transcript': {
      id: '/api/public/youtube-transcript'
      path: '/api/public/youtube-transcript'
      fullPath: '/api/public/youtube-transcript'
      preLoaderRoute: typeof ApiPublicYoutubeTranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kashier/renew': {
      id: '/api/public/kashier/renew'
      path: '/api/public/kashier/renew'
      fullPath: '/api/public/kashier/renew'
      preLoaderRoute: typeof ApiPublicKashierRenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kashier/return': {
      id: '/api/public/kashier/return'
      path: '/api/public/kashier/return'
      fullPath: '/api/public/kashier/return'
      preLoaderRoute: typeof ApiPublicKashierReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kashier/webhook': {
      id: '/api/public/kashier/webhook'
      path: '/api/public/kashier/webhook'
      fullPath: '/api/public/kashier/webhook'
      preLoaderRoute: typeof ApiPublicKashierWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactUsRoute: ContactUsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ApiActivityRoute: ApiActivityRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiAiRoute: ApiAiRoute,
  ApiKashierRoute: ApiKashierRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiQbankRoute: ApiQbankRoute,
  ApiSupportRoute: ApiSupportRoute,
  ApiPublicPeerStatsThresholdRoute: ApiPublicPeerStatsThresholdRoute,
  ApiPublicQbanksRoute: ApiPublicQbanksRoute,
  ApiPublicYoutubeTranscriptRoute: ApiPublicYoutubeTranscriptRoute,
  ApiPublicKashierRenewRoute: ApiPublicKashierRenewRoute,
  ApiPublicKashierReturnRoute: ApiPublicKashierReturnRoute,
  ApiPublicKashierWebhookRoute: ApiPublicKashierWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
