/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as ApiActivityRouteImport } from './routes/api/activity'
import { Route as ApiAdminRouteImport } from './routes/api/admin'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as ApiFeedbackRouteImport } from './routes/api/feedback'
import { Route as ApiKashierRouteImport } from './routes/api/kashier'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiPeerStatsRouteImport } from './routes/api/peer-stats'
import { Route as ApiQbankRouteImport } from './routes/api/qbank'
import { Route as ApiQbank_keyRouteImport } from './routes/api/qbank_key'
import { Route as ApiQbank_staticRouteImport } from './routes/api/qbank_static'
import { Route as ApiSupportRouteImport } from './routes/api/support'
import { Route as QbanksEgyptRouteImport } from './routes/qbanks/egypt'
import { Route as QbanksPlabRouteImport } from './routes/qbanks/plab'
import { Route as QbanksTunisiaRouteImport } from './routes/qbanks/tunisia'
import { Route as QbanksUsmleRouteImport } from './routes/qbanks/usmle'
import { Route as ApiApiActivityRouteImport } from './routes/api/api/activity'
import { Route as ApiApiAdminRouteImport } from './routes/api/api/admin'
import { Route as ApiApiAiRouteImport } from './routes/api/api/ai'
import { Route as ApiApiKashierRouteImport } from './routes/api/api/kashier'
import { Route as ApiApiNotificationsRouteImport } from './routes/api/api/notifications'
import { Route as ApiApiPeerStatsRouteImport } from './routes/api/api/peer-stats'
import { Route as ApiApiQbankRouteImport } from './routes/api/api/qbank'
import { Route as ApiApiQbank_keyRouteImport } from './routes/api/api/qbank_key'
import { Route as ApiApiQbank_staticRouteImport } from './routes/api/api/qbank_static'
import { Route as ApiApiSupportRouteImport } from './routes/api/api/support'
import { Route as ApiPublicPeerStatsThresholdRouteImport } from './routes/api/public/peer-stats-threshold'
import { Route as ApiPublicQbanksRouteImport } from './routes/api/public/qbanks'
import { Route as ApiPublicYoutubeTranscriptRouteImport } from './routes/api/public/youtube-transcript'
import { Route as ApiApiPublicPeerStatsThresholdRouteImport } from './routes/api/api/public/peer-stats-threshold'
import { Route as ApiApiPublicQbanksRouteImport } from './routes/api/api/public/qbanks'
import { Route as ApiApiPublicYoutubeTranscriptRouteImport } from './routes/api/api/public/youtube-transcript'
import { Route as ApiPublicKashierRenewRouteImport } from './routes/api/public/kashier/renew'
import { Route as ApiPublicKashierReturnRouteImport } from './routes/api/public/kashier/return'
import { Route as ApiPublicKashierWebhookRouteImport } from './routes/api/public/kashier/webhook'
import { Route as ApiApiPublicKashierRenewRouteImport } from './routes/api/api/public/kashier/renew'
import { Route as ApiApiPublicKashierReturnRouteImport } from './routes/api/api/public/kashier/return'
import { Route as ApiApiPublicKashierWebhookRouteImport } from './routes/api/api/public/kashier/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivityRoute = ApiActivityRouteImport.update({
  id: '/api/activity',
  path: '/api/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKashierRoute = ApiKashierRouteImport.update({
  id: '/api/kashier',
  path: '/api/kashier',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeerStatsRoute = ApiPeerStatsRouteImport.update({
  id: '/api/peer-stats',
  path: '/api/peer-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQbankRoute = ApiQbankRouteImport.update({
  id: '/api/qbank',
  path: '/api/qbank',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQbank_keyRoute = ApiQbank_keyRouteImport.update({
  id: '/api/qbank_key',
  path: '/api/qbank_key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQbank_staticRoute = ApiQbank_staticRouteImport.update({
  id: '/api/qbank_static',
  path: '/api/qbank_static',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupportRoute = ApiSupportRouteImport.update({
  id: '/api/support',
  path: '/api/support',
  getParentRoute: () => rootRouteImport,
} as any)
const QbanksEgyptRoute = QbanksEgyptRouteImport.update({
  id: '/qbanks/egypt',
  path: '/qbanks/egypt',
  getParentRoute: () => rootRouteImport,
} as any)
const QbanksPlabRoute = QbanksPlabRouteImport.update({
  id: '/qbanks/plab',
  path: '/qbanks/plab',
  getParentRoute: () => rootRouteImport,
} as any)
const QbanksTunisiaRoute = QbanksTunisiaRouteImport.update({
  id: '/qbanks/tunisia',
  path: '/qbanks/tunisia',
  getParentRoute: () => rootRouteImport,
} as any)
const QbanksUsmleRoute = QbanksUsmleRouteImport.update({
  id: '/qbanks/usmle',
  path: '/qbanks/usmle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiActivityRoute = ApiApiActivityRouteImport.update({
  id: '/api/api/activity',
  path: '/api/api/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiAdminRoute = ApiApiAdminRouteImport.update({
  id: '/api/api/admin',
  path: '/api/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiAiRoute = ApiApiAiRouteImport.update({
  id: '/api/api/ai',
  path: '/api/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiKashierRoute = ApiApiKashierRouteImport.update({
  id: '/api/api/kashier',
  path: '/api/api/kashier',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiNotificationsRoute = ApiApiNotificationsRouteImport.update({
  id: '/api/api/notifications',
  path: '/api/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiPeerStatsRoute = ApiApiPeerStatsRouteImport.update({
  id: '/api/api/peer-stats',
  path: '/api/api/peer-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiQbankRoute = ApiApiQbankRouteImport.update({
  id: '/api/api/qbank',
  path: '/api/api/qbank',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiQbank_keyRoute = ApiApiQbank_keyRouteImport.update({
  id: '/api/api/qbank_key',
  path: '/api/api/qbank_key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiQbank_staticRoute = ApiApiQbank_staticRouteImport.update({
  id: '/api/api/qbank_static',
  path: '/api/api/qbank_static',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiSupportRoute = ApiApiSupportRouteImport.update({
  id: '/api/api/support',
  path: '/api/api/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPeerStatsThresholdRoute =
  ApiPublicPeerStatsThresholdRouteImport.update({
    id: '/api/public/peer-stats-threshold',
    path: '/api/public/peer-stats-threshold',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicQbanksRoute = ApiPublicQbanksRouteImport.update({
  id: '/api/public/qbanks',
  path: '/api/public/qbanks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicYoutubeTranscriptRoute =
  ApiPublicYoutubeTranscriptRouteImport.update({
    id: '/api/public/youtube-transcript',
    path: '/api/public/youtube-transcript',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiApiPublicPeerStatsThresholdRoute =
  ApiApiPublicPeerStatsThresholdRouteImport.update({
    id: '/api/api/public/peer-stats-threshold',
    path: '/api/api/public/peer-stats-threshold',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiApiPublicQbanksRoute = ApiApiPublicQbanksRouteImport.update({
  id: '/api/api/public/qbanks',
  path: '/api/api/public/qbanks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiPublicYoutubeTranscriptRoute =
  ApiApiPublicYoutubeTranscriptRouteImport.update({
    id: '/api/api/public/youtube-transcript',
    path: '/api/api/public/youtube-transcript',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKashierRenewRoute = ApiPublicKashierRenewRouteImport.update({
  id: '/api/public/kashier/renew',
  path: '/api/public/kashier/renew',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKashierReturnRoute = ApiPublicKashierReturnRouteImport.update({
  id: '/api/public/kashier/return',
  path: '/api/public/kashier/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKashierWebhookRoute = ApiPublicKashierWebhookRouteImport.update({
  id: '/api/public/kashier/webhook',
  path: '/api/public/kashier/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiPublicKashierRenewRoute =
  ApiApiPublicKashierRenewRouteImport.update({
    id: '/api/api/public/kashier/renew',
    path: '/api/api/public/kashier/renew',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiApiPublicKashierReturnRoute =
  ApiApiPublicKashierReturnRouteImport.update({
    id: '/api/api/public/kashier/return',
    path: '/api/api/public/kashier/return',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiApiPublicKashierWebhookRoute =
  ApiApiPublicKashierWebhookRouteImport.update({
    id: '/api/api/public/kashier/webhook',
    path: '/api/api/public/kashier/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/ai': typeof ApiAiRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/kashier': typeof ApiKashierRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/peer-stats': typeof ApiPeerStatsRoute
  '/api/qbank': typeof ApiQbankRoute
  '/api/qbank_key': typeof ApiQbank_keyRoute
  '/api/qbank_static': typeof ApiQbank_staticRoute
  '/api/support': typeof ApiSupportRoute
  '/qbanks/egypt': typeof QbanksEgyptRoute
  '/qbanks/plab': typeof QbanksPlabRoute
  '/qbanks/tunisia': typeof QbanksTunisiaRoute
  '/qbanks/usmle': typeof QbanksUsmleRoute
  '/api/api/activity': typeof ApiApiActivityRoute
  '/api/api/admin': typeof ApiApiAdminRoute
  '/api/api/ai': typeof ApiApiAiRoute
  '/api/api/kashier': typeof ApiApiKashierRoute
  '/api/api/notifications': typeof ApiApiNotificationsRoute
  '/api/api/peer-stats': typeof ApiApiPeerStatsRoute
  '/api/api/qbank': typeof ApiApiQbankRoute
  '/api/api/qbank_key': typeof ApiApiQbank_keyRoute
  '/api/api/qbank_static': typeof ApiApiQbank_staticRoute
  '/api/api/support': typeof ApiApiSupportRoute
  '/api/public/peer-stats-threshold': typeof ApiPublicPeerStatsThresholdRoute
  '/api/public/qbanks': typeof ApiPublicQbanksRoute
  '/api/public/youtube-transcript': typeof ApiPublicYoutubeTranscriptRoute
  '/api/api/public/peer-stats-threshold': typeof ApiApiPublicPeerStatsThresholdRoute
  '/api/api/public/qbanks': typeof ApiApiPublicQbanksRoute
  '/api/api/public/youtube-transcript': typeof ApiApiPublicYoutubeTranscriptRoute
  '/api/public/kashier/renew': typeof ApiPublicKashierRenewRoute
  '/api/public/kashier/return': typeof ApiPublicKashierReturnRoute
  '/api/public/kashier/webhook': typeof ApiPublicKashierWebhookRoute
  '/api/api/public/kashier/renew': typeof ApiApiPublicKashierRenewRoute
  '/api/api/public/kashier/return': typeof ApiApiPublicKashierReturnRoute
  '/api/api/public/kashier/webhook': typeof ApiApiPublicKashierWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/ai': typeof ApiAiRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/kashier': typeof ApiKashierRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/peer-stats': typeof ApiPeerStatsRoute
  '/api/qbank': typeof ApiQbankRoute
  '/api/qbank_key': typeof ApiQbank_keyRoute
  '/api/qbank_static': typeof ApiQbank_staticRoute
  '/api/support': typeof ApiSupportRoute
  '/qbanks/egypt': typeof QbanksEgyptRoute
  '/qbanks/plab': typeof QbanksPlabRoute
  '/qbanks/tunisia': typeof QbanksTunisiaRoute
  '/qbanks/usmle': typeof QbanksUsmleRoute
  '/api/api/activity': typeof ApiApiActivityRoute
  '/api/api/admin': typeof ApiApiAdminRoute
  '/api/api/ai': typeof ApiApiAiRoute
  '/api/api/kashier': typeof ApiApiKashierRoute
  '/api/api/notifications': typeof ApiApiNotificationsRoute
  '/api/api/peer-stats': typeof ApiApiPeerStatsRoute
  '/api/api/qbank': typeof ApiApiQbankRoute
  '/api/api/qbank_key': typeof ApiApiQbank_keyRoute
  '/api/api/qbank_static': typeof ApiApiQbank_staticRoute
  '/api/api/support': typeof ApiApiSupportRoute
  '/api/public/peer-stats-threshold': typeof ApiPublicPeerStatsThresholdRoute
  '/api/public/qbanks': typeof ApiPublicQbanksRoute
  '/api/public/youtube-transcript': typeof ApiPublicYoutubeTranscriptRoute
  '/api/api/public/peer-stats-threshold': typeof ApiApiPublicPeerStatsThresholdRoute
  '/api/api/public/qbanks': typeof ApiApiPublicQbanksRoute
  '/api/api/public/youtube-transcript': typeof ApiApiPublicYoutubeTranscriptRoute
  '/api/public/kashier/renew': typeof ApiPublicKashierRenewRoute
  '/api/public/kashier/return': typeof ApiPublicKashierReturnRoute
  '/api/public/kashier/webhook': typeof ApiPublicKashierWebhookRoute
  '/api/api/public/kashier/renew': typeof ApiApiPublicKashierRenewRoute
  '/api/api/public/kashier/return': typeof ApiApiPublicKashierReturnRoute
  '/api/api/public/kashier/webhook': typeof ApiApiPublicKashierWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/ai': typeof ApiAiRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/kashier': typeof ApiKashierRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/peer-stats': typeof ApiPeerStatsRoute
  '/api/qbank': typeof ApiQbankRoute
  '/api/qbank_key': typeof ApiQbank_keyRoute
  '/api/qbank_static': typeof ApiQbank_staticRoute
  '/api/support': typeof ApiSupportRoute
  '/qbanks/egypt': typeof QbanksEgyptRoute
  '/qbanks/plab': typeof QbanksPlabRoute
  '/qbanks/tunisia': typeof QbanksTunisiaRoute
  '/qbanks/usmle': typeof QbanksUsmleRoute
  '/api/api/activity': typeof ApiApiActivityRoute
  '/api/api/admin': typeof ApiApiAdminRoute
  '/api/api/ai': typeof ApiApiAiRoute
  '/api/api/kashier': typeof ApiApiKashierRoute
  '/api/api/notifications': typeof ApiApiNotificationsRoute
  '/api/api/peer-stats': typeof ApiApiPeerStatsRoute
  '/api/api/qbank': typeof ApiApiQbankRoute
  '/api/api/qbank_key': typeof ApiApiQbank_keyRoute
  '/api/api/qbank_static': typeof ApiApiQbank_staticRoute
  '/api/api/support': typeof ApiApiSupportRoute
  '/api/public/peer-stats-threshold': typeof ApiPublicPeerStatsThresholdRoute
  '/api/public/qbanks': typeof ApiPublicQbanksRoute
  '/api/public/youtube-transcript': typeof ApiPublicYoutubeTranscriptRoute
  '/api/api/public/peer-stats-threshold': typeof ApiApiPublicPeerStatsThresholdRoute
  '/api/api/public/qbanks': typeof ApiApiPublicQbanksRoute
  '/api/api/public/youtube-transcript': typeof ApiApiPublicYoutubeTranscriptRoute
  '/api/public/kashier/renew': typeof ApiPublicKashierRenewRoute
  '/api/public/kashier/return': typeof ApiPublicKashierReturnRoute
  '/api/public/kashier/webhook': typeof ApiPublicKashierWebhookRoute
  '/api/api/public/kashier/renew': typeof ApiApiPublicKashierRenewRoute
  '/api/api/public/kashier/return': typeof ApiApiPublicKashierReturnRoute
  '/api/api/public/kashier/webhook': typeof ApiApiPublicKashierWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact-us'
    | '/login'
    | '/onboarding'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-of-service'
    | '/api/activity'
    | '/api/admin'
    | '/api/ai'
    | '/api/feedback'
    | '/api/kashier'
    | '/api/notifications'
    | '/api/peer-stats'
    | '/api/qbank'
    | '/api/qbank_key'
    | '/api/qbank_static'
    | '/api/support'
    | '/qbanks/egypt'
    | '/qbanks/plab'
    | '/qbanks/tunisia'
    | '/qbanks/usmle'
    | '/api/api/activity'
    | '/api/api/admin'
    | '/api/api/ai'
    | '/api/api/kashier'
    | '/api/api/notifications'
    | '/api/api/peer-stats'
    | '/api/api/qbank'
    | '/api/api/qbank_key'
    | '/api/api/qbank_static'
    | '/api/api/support'
    | '/api/public/peer-stats-threshold'
    | '/api/public/qbanks'
    | '/api/public/youtube-transcript'
    | '/api/api/public/peer-stats-threshold'
    | '/api/api/public/qbanks'
    | '/api/api/public/youtube-transcript'
    | '/api/public/kashier/renew'
    | '/api/public/kashier/return'
    | '/api/public/kashier/webhook'
    | '/api/api/public/kashier/renew'
    | '/api/api/public/kashier/return'
    | '/api/api/public/kashier/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact-us'
    | '/login'
    | '/onboarding'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-of-service'
    | '/api/activity'
    | '/api/admin'
    | '/api/ai'
    | '/api/feedback'
    | '/api/kashier'
    | '/api/notifications'
    | '/api/peer-stats'
    | '/api/qbank'
    | '/api/qbank_key'
    | '/api/qbank_static'
    | '/api/support'
    | '/qbanks/egypt'
    | '/qbanks/plab'
    | '/qbanks/tunisia'
    | '/qbanks/usmle'
    | '/api/api/activity'
    | '/api/api/admin'
    | '/api/api/ai'
    | '/api/api/kashier'
    | '/api/api/notifications'
    | '/api/api/peer-stats'
    | '/api/api/qbank'
    | '/api/api/qbank_key'
    | '/api/api/qbank_static'
    | '/api/api/support'
    | '/api/public/peer-stats-threshold'
    | '/api/public/qbanks'
    | '/api/public/youtube-transcript'
    | '/api/api/public/peer-stats-threshold'
    | '/api/api/public/qbanks'
    | '/api/api/public/youtube-transcript'
    | '/api/public/kashier/renew'
    | '/api/public/kashier/return'
    | '/api/public/kashier/webhook'
    | '/api/api/public/kashier/renew'
    | '/api/api/public/kashier/return'
    | '/api/api/public/kashier/webhook'
  id:
    | '__root__'
    | '/'
    | '/contact-us'
    | '/login'
    | '/onboarding'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-of-service'
    | '/api/activity'
    | '/api/admin'
    | '/api/ai'
    | '/api/feedback'
    | '/api/kashier'
    | '/api/notifications'
    | '/api/peer-stats'
    | '/api/qbank'
    | '/api/qbank_key'
    | '/api/qbank_static'
    | '/api/support'
    | '/qbanks/egypt'
    | '/qbanks/plab'
    | '/qbanks/tunisia'
    | '/qbanks/usmle'
    | '/api/api/activity'
    | '/api/api/admin'
    | '/api/api/ai'
    | '/api/api/kashier'
    | '/api/api/notifications'
    | '/api/api/peer-stats'
    | '/api/api/qbank'
    | '/api/api/qbank_key'
    | '/api/api/qbank_static'
    | '/api/api/support'
    | '/api/public/peer-stats-threshold'
    | '/api/public/qbanks'
    | '/api/public/youtube-transcript'
    | '/api/api/public/peer-stats-threshold'
    | '/api/api/public/qbanks'
    | '/api/api/public/youtube-transcript'
    | '/api/public/kashier/renew'
    | '/api/public/kashier/return'
    | '/api/public/kashier/webhook'
    | '/api/api/public/kashier/renew'
    | '/api/api/public/kashier/return'
    | '/api/api/public/kashier/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactUsRoute: typeof ContactUsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ApiActivityRoute: typeof ApiActivityRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiKashierRoute: typeof ApiKashierRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiPeerStatsRoute: typeof ApiPeerStatsRoute
  ApiQbankRoute: typeof ApiQbankRoute
  ApiQbank_keyRoute: typeof ApiQbank_keyRoute
  ApiQbank_staticRoute: typeof ApiQbank_staticRoute
  ApiSupportRoute: typeof ApiSupportRoute
  QbanksEgyptRoute: typeof QbanksEgyptRoute
  QbanksPlabRoute: typeof QbanksPlabRoute
  QbanksTunisiaRoute: typeof QbanksTunisiaRoute
  QbanksUsmleRoute: typeof QbanksUsmleRoute
  ApiApiActivityRoute: typeof ApiApiActivityRoute
  ApiApiAdminRoute: typeof ApiApiAdminRoute
  ApiApiAiRoute: typeof ApiApiAiRoute
  ApiApiKashierRoute: typeof ApiApiKashierRoute
  ApiApiNotificationsRoute: typeof ApiApiNotificationsRoute
  ApiApiPeerStatsRoute: typeof ApiApiPeerStatsRoute
  ApiApiQbankRoute: typeof ApiApiQbankRoute
  ApiApiQbank_keyRoute: typeof ApiApiQbank_keyRoute
  ApiApiQbank_staticRoute: typeof ApiApiQbank_staticRoute
  ApiApiSupportRoute: typeof ApiApiSupportRoute
  ApiPublicPeerStatsThresholdRoute: typeof ApiPublicPeerStatsThresholdRoute
  ApiPublicQbanksRoute: typeof ApiPublicQbanksRoute
  ApiPublicYoutubeTranscriptRoute: typeof ApiPublicYoutubeTranscriptRoute
  ApiApiPublicPeerStatsThresholdRoute: typeof ApiApiPublicPeerStatsThresholdRoute
  ApiApiPublicQbanksRoute: typeof ApiApiPublicQbanksRoute
  ApiApiPublicYoutubeTranscriptRoute: typeof ApiApiPublicYoutubeTranscriptRoute
  ApiPublicKashierRenewRoute: typeof ApiPublicKashierRenewRoute
  ApiPublicKashierReturnRoute: typeof ApiPublicKashierReturnRoute
  ApiPublicKashierWebhookRoute: typeof ApiPublicKashierWebhookRoute
  ApiApiPublicKashierRenewRoute: typeof ApiApiPublicKashierRenewRoute
  ApiApiPublicKashierReturnRoute: typeof ApiApiPublicKashierReturnRoute
  ApiApiPublicKashierWebhookRoute: typeof ApiApiPublicKashierWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activity': {
      id: '/api/activity'
      path: '/api/activity'
      fullPath: '/api/activity'
      preLoaderRoute: typeof ApiActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kashier': {
      id: '/api/kashier'
      path: '/api/kashier'
      fullPath: '/api/kashier'
      preLoaderRoute: typeof ApiKashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/peer-stats': {
      id: '/api/peer-stats'
      path: '/api/peer-stats'
      fullPath: '/api/peer-stats'
      preLoaderRoute: typeof ApiPeerStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qbank': {
      id: '/api/qbank'
      path: '/api/qbank'
      fullPath: '/api/qbank'
      preLoaderRoute: typeof ApiQbankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qbank_key': {
      id: '/api/qbank_key'
      path: '/api/qbank_key'
      fullPath: '/api/qbank_key'
      preLoaderRoute: typeof ApiQbank_keyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qbank_static': {
      id: '/api/qbank_static'
      path: '/api/qbank_static'
      fullPath: '/api/qbank_static'
      preLoaderRoute: typeof ApiQbank_staticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/support': {
      id: '/api/support'
      path: '/api/support'
      fullPath: '/api/support'
      preLoaderRoute: typeof ApiSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qbanks/egypt': {
      id: '/qbanks/egypt'
      path: '/qbanks/egypt'
      fullPath: '/qbanks/egypt'
      preLoaderRoute: typeof QbanksEgyptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qbanks/plab': {
      id: '/qbanks/plab'
      path: '/qbanks/plab'
      fullPath: '/qbanks/plab'
      preLoaderRoute: typeof QbanksPlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qbanks/tunisia': {
      id: '/qbanks/tunisia'
      path: '/qbanks/tunisia'
      fullPath: '/qbanks/tunisia'
      preLoaderRoute: typeof QbanksTunisiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qbanks/usmle': {
      id: '/qbanks/usmle'
      path: '/qbanks/usmle'
      fullPath: '/qbanks/usmle'
      preLoaderRoute: typeof QbanksUsmleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api/activity': {
      id: '/api/api/activity'
      path: '/api/api/activity'
      fullPath: '/api/api/activity'
      preLoaderRoute: typeof ApiApiActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api/admin': {
      id: '/api/api/admin'
      path: '/api/api/admin'
      fullPath: '/api/api/admin'
      preLoaderRoute: typeof ApiApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api/ai': {
      id: '/api/api/ai'
      path: '/api/api/ai'
      fullPath: '/api/api/ai'
      preLoaderRoute: typeof ApiApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api/kashier': {
      id: '/api/api/kashier'
      path: '/api/api/kashier'
      fullPath: '/api/api/kashier'
      preLoaderRoute: typeof ApiApiKashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api/notifications': {
      id: '/api/api/notifications'
      path: '/api/api/notifications'
      fullPath: '/api/api/notifications'
      preLoaderRoute: typeof ApiApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api/peer-stats': {
      id: '/api/api/peer-stats'
      path: '/api/api/peer-stats'
      fullPath: '/api/api/peer-stats'
      preLoaderRoute: typeof ApiApiPeerStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api/qbank': {
      id: '/api/api/qbank'
      path: '/api/api/qbank'
      fullPath: '/api/api/qbank'
      preLoaderRoute: typeof ApiApiQbankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api/qbank_key': {
      id: '/api/api/qbank_key'
      path: '/api/api/qbank_key'
      fullPath: '/api/api/qbank_key'
      preLoaderRoute: typeof ApiApiQbank_keyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api/qbank_static': {
      id: '/api/api/qbank_static'
      path: '/api/api/qbank_static'
      fullPath: '/api/api/qbank_static'
      preLoaderRoute: typeof ApiApiQbank_staticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api/support': {
      id: '/api/api/support'
      path: '/api/api/support'
      fullPath: '/api/api/support'
      preLoaderRoute: typeof ApiApiSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/peer-stats-threshold': {
      id: '/api/public/peer-stats-threshold'
      path: '/api/public/peer-stats-threshold'
      fullPath: '/api/public/peer-stats-threshold'
      preLoaderRoute: typeof ApiPublicPeerStatsThresholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/qbanks': {
      id: '/api/public/qbanks'
      path: '/api/public/qbanks'
      fullPath: '/api/public/qbanks'
      preLoaderRoute: typeof ApiPublicQbanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/youtube-transcript': {
      id: '/api/public/youtube-transcript'
      path: '/api/public/youtube-transcript'
      fullPath: '/api/public/youtube-transcript'
      preLoaderRoute: typeof ApiPublicYoutubeTranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api/public/peer-stats-threshold': {
      id: '/api/api/public/peer-stats-threshold'
      path: '/api/api/public/peer-stats-threshold'
      fullPath: '/api/api/public/peer-stats-threshold'
      preLoaderRoute: typeof ApiApiPublicPeerStatsThresholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api/public/qbanks': {
      id: '/api/api/public/qbanks'
      path: '/api/api/public/qbanks'
      fullPath: '/api/api/public/qbanks'
      preLoaderRoute: typeof ApiApiPublicQbanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api/public/youtube-transcript': {
      id: '/api/api/public/youtube-transcript'
      path: '/api/api/public/youtube-transcript'
      fullPath: '/api/api/public/youtube-transcript'
      preLoaderRoute: typeof ApiApiPublicYoutubeTranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kashier/renew': {
      id: '/api/public/kashier/renew'
      path: '/api/public/kashier/renew'
      fullPath: '/api/public/kashier/renew'
      preLoaderRoute: typeof ApiPublicKashierRenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kashier/return': {
      id: '/api/public/kashier/return'
      path: '/api/public/kashier/return'
      fullPath: '/api/public/kashier/return'
      preLoaderRoute: typeof ApiPublicKashierReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kashier/webhook': {
      id: '/api/public/kashier/webhook'
      path: '/api/public/kashier/webhook'
      fullPath: '/api/public/kashier/webhook'
      preLoaderRoute: typeof ApiPublicKashierWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api/public/kashier/renew': {
      id: '/api/api/public/kashier/renew'
      path: '/api/api/public/kashier/renew'
      fullPath: '/api/api/public/kashier/renew'
      preLoaderRoute: typeof ApiApiPublicKashierRenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api/public/kashier/return': {
      id: '/api/api/public/kashier/return'
      path: '/api/api/public/kashier/return'
      fullPath: '/api/api/public/kashier/return'
      preLoaderRoute: typeof ApiApiPublicKashierReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api/public/kashier/webhook': {
      id: '/api/api/public/kashier/webhook'
      path: '/api/api/public/kashier/webhook'
      fullPath: '/api/api/public/kashier/webhook'
      preLoaderRoute: typeof ApiApiPublicKashierWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactUsRoute: ContactUsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ApiActivityRoute: ApiActivityRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiAiRoute: ApiAiRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiKashierRoute: ApiKashierRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiPeerStatsRoute: ApiPeerStatsRoute,
  ApiQbankRoute: ApiQbankRoute,
  ApiQbank_keyRoute: ApiQbank_keyRoute,
  ApiQbank_staticRoute: ApiQbank_staticRoute,
  ApiSupportRoute: ApiSupportRoute,
  QbanksEgyptRoute: QbanksEgyptRoute,
  QbanksPlabRoute: QbanksPlabRoute,
  QbanksTunisiaRoute: QbanksTunisiaRoute,
  QbanksUsmleRoute: QbanksUsmleRoute,
  ApiApiActivityRoute: ApiApiActivityRoute,
  ApiApiAdminRoute: ApiApiAdminRoute,
  ApiApiAiRoute: ApiApiAiRoute,
  ApiApiKashierRoute: ApiApiKashierRoute,
  ApiApiNotificationsRoute: ApiApiNotificationsRoute,
  ApiApiPeerStatsRoute: ApiApiPeerStatsRoute,
  ApiApiQbankRoute: ApiApiQbankRoute,
  ApiApiQbank_keyRoute: ApiApiQbank_keyRoute,
  ApiApiQbank_staticRoute: ApiApiQbank_staticRoute,
  ApiApiSupportRoute: ApiApiSupportRoute,
  ApiPublicPeerStatsThresholdRoute: ApiPublicPeerStatsThresholdRoute,
  ApiPublicQbanksRoute: ApiPublicQbanksRoute,
  ApiPublicYoutubeTranscriptRoute: ApiPublicYoutubeTranscriptRoute,
  ApiApiPublicPeerStatsThresholdRoute: ApiApiPublicPeerStatsThresholdRoute,
  ApiApiPublicQbanksRoute: ApiApiPublicQbanksRoute,
  ApiApiPublicYoutubeTranscriptRoute: ApiApiPublicYoutubeTranscriptRoute,
  ApiPublicKashierRenewRoute: ApiPublicKashierRenewRoute,
  ApiPublicKashierReturnRoute: ApiPublicKashierReturnRoute,
  ApiPublicKashierWebhookRoute: ApiPublicKashierWebhookRoute,
  ApiApiPublicKashierRenewRoute: ApiApiPublicKashierRenewRoute,
  ApiApiPublicKashierReturnRoute: ApiApiPublicKashierReturnRoute,
  ApiApiPublicKashierWebhookRoute: ApiApiPublicKashierWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
